"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, CalendarDays, ChevronDown, GraduationCap, Landmark, Mail, MapPin, Menu, Microscope, MonitorSmartphone, Music2, Phone, ShieldCheck, Sparkles, Trophy, Users, X } from "lucide-react";

const media="https://mpconventschool.com/wp-content/uploads/2024/08/";
const slides=["banner-12.jpg","banner-13.jpg","banner-3.jpg"];
const nav=["Home","About Us","Academics","Admissions","Campus","Student Zone","Gallery","Contact Us"];
const features=[
 [Users,"Experienced Faculty","Dedicated educators focused on every child’s learning and development."],
 [MonitorSmartphone,"Digital Classrooms","Technology-enabled learning for engaging classroom experiences."],
 [Microscope,"Learning Facilities","Activity, research and reading spaces that encourage discovery."],
 [Trophy,"Sports & Activities","Sports and co-curricular opportunities for balanced growth."],
 [ShieldCheck,"Caring Environment","A disciplined, supportive campus where children learn confidently."],
 [BookOpen,"NEXT ERP & Parent App","Easy digital access for parents and students through the existing ERP."],
] as const;
const programs=[
 ["col1-1.jpg","Pre-Primary","Nursery & Early Years","A joyful beginning that builds curiosity, confidence and healthy learning habits."],
 ["col2-1.jpg","Primary","Foundational Learning","Strong concepts, communication and collaboration through enriching experiences."],
 ["banner-1.jpeg","Middle School","Growing Independence","Subject mastery, creativity and critical thinking for 21st-century learners."],
 ["banner-10.jpeg","Secondary & Senior Secondary","Classes IX–XII","Focused academic preparation, guidance and opportunities for future success."],
] as const;
const facilities=[["banner-6.jpg","Digital Classes",MonitorSmartphone],["banner-2.jpeg","Activity Room",Sparkles],["banner-11.png","Research & Learning",Microscope],["banner-4.jpg","Reading Room",BookOpen],["banner-5.png","Dance & Activities",Music2],["banner-13.jpg","Sports",Trophy]] as const;

export default function Home(){
 const [menu,setMenu]=useState(false),[slide,setSlide]=useState(0);
 useEffect(()=>{const t=setInterval(()=>setSlide(s=>(s+1)%slides.length),5500);return()=>clearInterval(t)},[]);
 return <main>
  <header className="site-header">
   <div className="topbar"><div className="container top-inner"><span><MapPin/> Ward No. 6, Shaktinagar, Bari, Distt. Raisen, M.P.</span><div><a href="tel:07582222427"><Phone/>07582-222427</a><a href="tel:9899627828">9899627828</a><a href="mailto:mpconventbari@gmail.com"><Mail/>mpconventbari@gmail.com</a><b>f</b><b>▶</b></div></div></div>
   <div className="navbar"><div className="container nav-inner"><a href="#home"><Image className="logo" src={`${media}mp-convent-logo.png`} alt="MP Convent School Bari" width={369} height={75} priority/></a><nav className={menu?"open":""}>{nav.map((n,i)=><a key={n} href={`#${n.toLowerCase().replaceAll(" ","-")}`} onClick={()=>setMenu(false)}>{n}{i>0&&i<6?<ChevronDown/>:null}</a>)}<a className="mobile-erp" href="https://mpconvent.nexterp.in">ERP Login</a></nav><div className="nav-actions"><a className="erp" href="https://mpconvent.nexterp.in">ERP Login</a><a className="btn gold" href="#admissions">Apply Online</a><button onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button></div></div></div>
  </header>
  <section className="hero" id="home">{slides.map((s,i)=><div key={s} className={`slide ${i===slide?"active":""}`}><Image src={`${media}${s}`} alt="MP Convent School campus" fill priority={i===0} sizes="100vw"/></div>)}<div className="shade"/><div className="container hero-copy"><p className="script">Admissions Open</p><h1><strong>2026–27</strong>A Place where Learning<br/>Becomes a Journey.</h1><p>At MP Convent School, we nurture young minds to become confident, responsible and compassionate leaders of tomorrow.</p><div className="hero-actions"><a className="btn gold" href="#admissions">Apply Online <ArrowRight/></a><a className="btn outline" href="#contact-us">Book a Campus Visit</a></div><div className="dots">{slides.map((_,i)=><button key={i} className={i===slide?"active":""} onClick={()=>setSlide(i)} aria-label={`Slide ${i+1}`}/>)}</div></div></section>
  <section className="high-wrap"><div className="container highlights">{[[GraduationCap,"Since 1996","A tradition of education"],[Landmark,"CBSE Affiliated","New Delhi"],[MonitorSmartphone,"Smart Learning","Digital classrooms"],[BookOpen,"Nursery–XII","Admissions open"],[ShieldCheck,"Holistic Growth","Learning beyond books"]].map(([Icon,a,b])=><div className="highlight" key={String(a)}><span><Icon/></span><div><b>{String(a)}</b><small>{String(b)}</small></div></div>)}</div></section>
  <section className="section why" id="about-us"><div className="container"><Title over="WHY CHOOSE MP CONVENT SCHOOL?" title="Holistic Education for a Better Tomorrow"/><div className="features">{features.map(([Icon,t,d])=><article key={t}><Icon/><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="section" id="academics"><div className="container"><Title over="LEARNING AT EVERY STAGE" title="Our Academic Programs"/><div className="programs">{programs.map(([im,t,c,d])=><article key={t}><div className="program-img"><Image src={`${media}${im}`} alt={t} fill sizes="(max-width:700px) 100vw,25vw"/></div><div className="program-body"><small>{c}</small><h3>{t}</h3><p>{d}</p><a href="#academics">Explore More <ArrowRight/></a></div></article>)}</div></div></section>
  <section className="stats"><div className="container">{[["1996","Established"],["CBSE","Affiliated School"],["Digital","Classrooms"],["Holistic","Activities"],["Nursery–XII","Admission Enquiry"]].map(([a,b])=><div key={a}><strong>{a}</strong><span>{b}</span></div>)}</div></section>
  <section className="section about"><div className="container split"><div className="about-img"><Image src={`${media}banner1-1-768x363-1.jpg`} alt="School campus" fill sizes="(max-width:800px) 100vw,50vw"/></div><div><p className="over">ABOUT MP CONVENT SCHOOL</p><h2>A Tradition of Learning Since 1996</h2><p>M.P. Convent School’s journey of excellence began in 1996. The English-medium CBSE institution in Bari, Raisen recognizes, nurtures and treasures the uniqueness of every child.</p><blockquote>“Our mission is to provide positive catalytic impulses to every child to stretch inherent learning competencies through self-discovery.”</blockquote><a className="btn navy" href="#about-us">Read Our Story <ArrowRight/></a></div></div></section>
  <section className="section campus" id="campus"><div className="container"><Title over="SPACES THAT INSPIRE" title="Explore Our Campus" text="Purposeful learning spaces and activities that help every learner discover new interests."/><div className="facilities">{facilities.map(([im,t,Icon])=><article key={t}><Image src={`${media}${im}`} alt={t} fill sizes="(max-width:700px) 100vw,33vw"/><div><Icon/><h3>{t}</h3></div></article>)}</div></div></section>
  <section className="section updates" id="gallery"><div className="container update-grid"><div><Head title="News & Events"/>{["Admissions Open 2026–27","Learning Beyond the Classroom","Celebrating Student Participation"].map((t,i)=><article className="news" key={t}><span><CalendarDays/><b>{i+8}</b><small>SEP</small></span><div><h3>{t}</h3><p>{i===0?"Admission enquiries are open from Nursery to Class XII.":"Campus updates, activities and student moments from MP Convent School."}</p></div></article>)}</div><div><Head title="Gallery Highlights"/><div className="gallery">{["banner-5.png","banner-11.png","banner-4.jpg","banner-13.jpg","banner-6.jpg","banner-12.jpg"].map((im,i)=><div className={i===0?"wide":""} key={im}><Image src={`${media}${im}`} alt="School activity" fill sizes="(max-width:700px) 50vw,25vw"/></div>)}</div></div></div></section>
  <section className="admission" id="admissions"><div className="container admission-grid"><div><p className="over">ADMISSIONS 2026–27</p><h2>Begin Your Child’s Journey With Us</h2><p>Speak with our admission team, plan a campus visit or submit a quick enquiry today.</p><div className="chips"><a href="tel:07582222427"><Phone/>07582-222427</a><a href="https://wa.me/919899627828">WA 9899627828</a></div></div><form onSubmit={e=>e.preventDefault()}><h3>Admission Enquiry</h3><div className="form-grid"><label>Parent Name<input required placeholder="Enter full name"/></label><label>Mobile Number<input required type="tel" placeholder="10-digit number"/></label><label>Student Name<input required placeholder="Student name"/></label><label>Class Applying For<select required defaultValue=""><option value="" disabled>Select class</option><option>Nursery</option><option>KG</option><option>Class I–V</option><option>Class VI–VIII</option><option>Class IX–XII</option></select></label></div><label>Message<textarea rows={3} placeholder="How can we help?"/></label><button className="btn gold">Submit Enquiry <ArrowRight/></button></form></div></section>
  <section className="contact-bar" id="contact-us"><div className="container"><div><Phone/><span><b>Have Questions?</b>We are here to help!</span></div><a href="tel:07582222427">Call 07582-222427</a><a className="wa" href="https://wa.me/919899627828">WhatsApp 9899627828</a><a className="enquire" href="#admissions">Enquire Now <ArrowRight/></a></div></section>
  <footer><div className="container footer-grid"><div className="footer-brand"><Image src={`${media}mp-convent-logo.png`} alt="MP Convent School" width={295} height={60}/><p>An English-medium CBSE school dedicated to nurturing every child through learning, values and holistic development.</p></div><Links title="Quick Links" items={["Home","About Us","Academics","Admissions","Campus"]}/><Links title="Student Zone" items={["NLP / ERP Login","TC Download","Book Details","Fee Structure","Academic Calendar"]}/><Links title="Useful Links" items={["Important Documents","CBSE Information","MPD","Rules & Regulations","Gallery"]}/><div><h3>Contact Us</h3><p>Ward No. 6, Shaktinagar, Bari, Distt. Raisen, M.P. – 464665</p><p>07582-222427<br/>9899627828</p><p>mpconventbari@gmail.com</p></div></div><div className="container copyright"><span>© 2026 MP Convent School. All Rights Reserved.</span><span>Privacy Policy &nbsp;|&nbsp; Terms & Conditions</span></div></footer>
  <a className="float-call" href="tel:07582222427"><Phone/></a><a className="float-wa" href="https://wa.me/919899627828">WA</a>
 </main>
}
function Title({over,title,text}:{over:string,title:string,text?:string}){return <div className="title"><p className="over">{over}</p><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
function Head({title}:{title:string}){return <div className="head"><div><p className="over">STAY UPDATED</p><h2>{title}</h2></div><a href="#gallery">View All <ArrowRight/></a></div>}
function Links({title,items}:{title:string,items:string[]}){return <div><h3>{title}</h3><ul>{items.map(x=><li key={x}><a href="#">{x}</a></li>)}</ul></div>}
